language: php
cache:
    directories:
        - $HOME/.composer/cache/files
php:
    - '7.1'
    - '7.2'
    - '7.3'
install: composer install
after_success:
    - travis_retry php vendor/bin/php-coveralls
