language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
cache:
    directories:
        - $HOME/.composer/cache/files
install: composer install
script:
    - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_success:
    - travis_retry php vendor/bin/php-coveralls
